= Test di usabilità: Informazioni utili
Andrea Esposito <a.esposito39@studenti.uniba.it>; Alessandro Annese <a.annese23@studenti.uniba.it>; Davide De Salvo <d.desalvo@studenti.uniba.it>; Graziano Montanaro <g.montanaro16@studenti.uniba.it>; Regina Zaccaria <r.zaccaria14@studenti.uniba.it>
v1.0.0, 10 gennaio 2019: Stesura del documento "README"
:toc: left
:doctype: article
:sectnums:
:partnums:
:sectnumsdepth: 5
:xrefstyle: short
:media: prepress
include::./src/locale/attributes.adoc[]

== Informazioni di base

[horizontal]
Università:: Università degli Studi di Bari "`A. Moro`" (sede di Taranto)
Corso di Laurea:: Informatica e Comunicazione Digitale
Corso:: Interazione Uomo Macchina
Anno Accademico:: 2019/2020
Contatti del referente:: {author} <{email}>

Una versione HTML online del report è disponibile al seguente link:
https://espositoandrea.github.io/ReportIUM/[espositoandrea.github.io/ReportIUM].
Si noti che tale sito web sarà chiuso poco dopo l'appello d'esame e ha il solo
scopo di rendere più leggibile la documentazione.

WARNING: Il team ha notato durante le varie sessioni di valutazione che il sito
web in oggetto subiva frequenti variazioni e modifiche. Per questo motivo, lo
stato del sito nel momento in cui si legge questo documento potrebbe essere
diverso da quello che il team ha valutato. Per questo motivo tutte le
segnalazioni e le valutazioni descritte sono da intendersi valide solo per il
sito nello stato in cui era alla data della valutazione stessa (tale data è
quindi riportata se necessaria).


== Il gruppo di lavoro

Il gruppo che ha effettuato questa valutazione di usabilità è il gruppo "`**FSC --
Five Students of Computer Science**`", composto dai seguenti studenti (riportati
in ordine alfabetico).

[cols="<.^,^.^,>.^", options="header"]
|===
|Nome e cognome|Matricola|E-Mail
|Alessandro Annese|676964|a.annese23@studenti.uniba.it
|Davide De Salvo|676502|d.desalvo@studenti.uniba.it
|Andrea Esposito|677021|a.esposito39@studenti.uniba.it
|Graziano Montanaro|677909|g.montanaro16@studenti.uniba.it
|Regina Zaccaria|675888|r.zaccaria14@studenti.uniba.it
|===

== Lo ZIP consegnato

Lo ZIP consegnato contiene due cartelle (oltre il presente file): la cartella
`report/`, contenente tutto il materiale prodotto dal team, e la cartella
`slides/`, contenente la presentazione del progetto. Si riporta di seguito una
descrizione di tutti i file consegnati.

`report/`::
    Questa cartella rappresenta la consegna del team.

    `report/euristica/`:::
        Questa cartella contiene tutte le tabelle di valutazione euristica
        prodotte dal team.
        
        `report/euristica/alessandro.pdf`::::
            La tabella di valutazione prodotta da {author_2}.
        `report/euristica/andrea.pdf`::::
            La tabella di valutazione prodotta da {author}.
        `report/euristica/complessiva.pdf`::::
            La tabella di valutazione prodotta complessiva finale prodotta
            dall'intero team dopo una discussione delle tabelle individuali.
        `report/euristica/davide.pdf`::::
            La tabella di valutazione prodotta da {author_3}.
        `report/euristica/graziano.pdf`::::
            La tabella di valutazione prodotta da {author_4}.
        `report/euristica/regina.pdf`::::
            La tabella di valutazione prodotta da {author_5}.

    `report/ReportIUM.pdf`::: 
        Questo documento è la relazione del test prodotta dal team.

`slides/`::
    Questa cartella contiene la presentazione PowerPoint mostrata durante
    l'esame orale.
    
    `slides/Presentazione.pptx`:::
        La presentazione PowerPoint mostrata durante la prova orale.
    `slides/Presentazione.pdf`:::
        La presentazione PowerPoint mostrata durante la prova orale (in formato
        PDF).

`README.html`:: Questo file.

== Note aggiuntive

* Il team, durante la fase di valutazione con tecnica _thinking aloud_, ha
  registrato alcune sessioni di test, al fine di migliorare e semplificare le
  operazioni di stesura dei rapporti finali. Gli utenti sono stati avvertiti e
  hanno firmato una liberatoria. Se necessario, il team è disposto a inviare i
  video degli utenti che hanno dato la disponibilità alla registrazione e alla
  condivisione (_solo_ con la docente) del materiale.
