== Valutazione euristica

Nelle seguenti tabelle di valutazione, la gravità è espressa in una scala di
interi nell'intervallo +[1, 5]+, dove 1 indica un problema lieve e 5 un problema
grave.

=== Tabelle di valutazione parziali

Di seguito si riportano le tabelle parziali dei valutatori. Ogni tabella è
seguita da ulteriori commenti forniti dal membro del team (se presenti).

==== Tabella di {author_2}

include::../../heuristic/alessandro/table.adoc[]

===== Commenti

include::../../heuristic/alessandro/comments.adoc[]

==== Tabella di {author_3}

include::../../heuristic/davide/table.adoc[]

==== Tabella di {author}

include::../../heuristic/andrea/table.adoc[]

===== Commenti

include::../../heuristic/andrea/comments.adoc[]

==== Tabella di {author_4}

include::../../heuristic/graziano/table.adoc[]

==== Tabella di {author_5}

include::../../heuristic/regina/table.adoc[]

=== Tabella di valutazione complessiva

Si riporta nella <<tab-valutazione-euristica>> la tabella di valutazione
euristica complessiva che il team ha prodotto in seguito a una discussione interna.

include::../../heuristic/complessiva/table.adoc[]

==== Commenti

include::../../heuristic/complessiva/comments.adoc[]

== Metodologia thinking aloud

La procedura del test descritta di seguito è stata seguita e rispettata durante
tutti i test condotti. Gli utenti sono stati inizialmente introdotti al team di
lavoro presente durante la sessione e agli obiettivi del test. Successivamente,
dopo un breve questionario demografico conoscitivo, vengono introdotti alla
metodologia del test e sono informati circa la necessità di registrare video e
audio (per ridurre la possibilità di perdita di informazioni dovute a errori
umani degli osservatori).  Viene quindi proposta una breve introduzione di
quanto è richiesto, sottolineando che le attività non sono finalizzate alla
valutazione del tester ma alla sola valutazione del sito e all'identificazione
di eventuali problematiche legate a esso. Sono rese note alcune richieste
ulteriori della valutazione, per cui:

* Si vieta l'utilizzo della barra e degli strumenti di ricerca disponibili nella
  pagina principale.
* Si vieta l'utilizzo della mappa del sito web al fine di valutare la
  raggiungibilità delle pagine.
* Si richiede al tester di "`ragionare ad alta voce`" mentre utilizza il sito.

Sono rese inoltre note alcune indicazioni circa le modalità di svolgimento del
test, ovverosia:

* Nel caso in cui si ritenga di aver raggiunto l'obiettivo lo si dovrà
  comunicare al facilitatore.
* Nel caso in cui si ritenga di non essere in grado di raggiungere l'obiettivo
  lo si dovrà comunicare al facilitatore.
* Il facilitatore non può esprimere valutazioni circa l'operato del tester
* Il facilitatore non può fornire indicazioni circa le azioni da svolgere per il
  raggiungimento dell'obiettivo, se non al fine di pilotare l'attenzione
  dell'utente verso alcune pagine (al fine di valutarle) una volta che il test
  del task risulta essere completato (a prescindere dalla riuscita).
* Al termine di ogni task l'utente deve tornare alla home page del sito.

Agli utenti è poi notificata la necessità di compilare un questionario al fine
di esprimere una valutazione quantitativa dell'usabilità del sito web.

I report presentati in <<report-dei-test>> sono stati stesi dai relativi
osservatori e sono stati poi discussi dall'intero team.

Si presenta di seguito una tabella riepilogativa (<<tab-demografica-partecipanti>>)
contenente le informazioni demografiche raccolte sugli utenti partecipanti.

include::../tables/tab-demografica-partecipanti.adoc[]

[[report-dei-test]]
=== Report dei test

include::tester-1/report.adoc[leveloffset=+3]

include::tester-2/report.adoc[leveloffset=+3]

include::tester-3/report.adoc[leveloffset=+3]

include::tester-4/report.adoc[leveloffset=+3]

include::tester-5/report.adoc[leveloffset=+3]

include::tester-6/report.adoc[leveloffset=+3]

=== Risultati complessivi 

Si riporta in <<tab-successo-task>>, per ogni tester, lo stato di ogni task
(superato o non superato). Inoltre si riporta il tasso di successo per task, il
tasso di successo per partecipante e il tasso di successo complessivo.

include::tasks/successo.adoc[]

==== Risultati Net Promoter Score

[cols="^.^, ^.^", frame=none, grid=none]
|===
a|
[[fig-risultati-nps]]
.Un diagramma a torta rappresentante la suddivisione dell'utenza nelle classi "`Promotori`", "`Neutri`" o "`Detrattori`" derivante dai questionari NPS
image::./images/fig-risultati-nps.svg[role=right]

a|
[[fig-risultati-nps-boxplot]]
.Un _box plot_ rappresentante la disposizione delle valutazioni del questionario NPS
image::./images/fig-risultati-nps-boxplot.svg[role=right]
|===

Si riporta in <<fig-risultati-nps>> e in <<fig-risultati-nps-boxplot>> un
riepilogo dei risultati del questionario _Net Promoter Score (NPS)_. È evidente
dall'assenza totale di utenti promotori del sito che sono state riscontrate
diverse difficoltà nel suo utilizzo: sono evidentemente preponderanti, infatti,
gli utenti detrattori del sito.

include::../tables/nps-score.adoc[]


==== Risultati del System Usability Scale

Si riportano nelle varie tabele successive un riepilogo dei risultati dei questionari SUS somministrati.

include::../tables/sus/tester1.adoc[]

include::../tables/sus/tester2.adoc[]

include::../tables/sus/tester3.adoc[]

include::../tables/sus/tester4.adoc[]

include::../tables/sus/tester5.adoc[]

include::../tables/sus/tester6.adoc[]

===== Risultati complessivi

Si riporta nella <<tab-sus-complessiva>> un riepilogo complessivo di tutte le
valutazioni SUS ricevute.

include::../tables/sus/complessiva.adoc[]

include::../tables/sus-score.adoc[]

Il punteggio complessivo è di *29.17*, un punteggio molto basso che sottolinea
una scarsa usabilità del sito. Questo risultato è in linea con le previsioni che
è possibile fare guardando solo la tabella di valutazione euristica
(<<tab-valutazione-euristica>>), dove quasi tutti i problemi riscontrati sono
caratterizzati da una gravità alta.

