[#il-gruppo-di-lavoro]
== Il gruppo di lavoro

Il gruppo di lavoro responsabile delle attività di valutazione documentate nel
presente documento è il gruppo "`FSC`" del corso di Interazione Uomo-Macchina
dell'Anno Accademico 2019/20.

=== I membri del gruppo di lavoro

Nella tabella <<tab-gruppo-lavoro>> si riportano alcuni dati dei valutatori
appartenenti al gruppo di valutazione.

.Il gruppo di lavoro "`FSC`"
[#tab-gruppo-lavoro]
[cols="<1,<1", options="header"]
|===
|Nome|Cognome
|{firstname_2}|{lastname_2}
|{firstname_3}|{lastname_3}
|{firstname}|{lastname}
|{firstname_4}|{lastname_4}
|{firstname_5}|{lastname_5}
|===

=== Ruoli

Lo svolgimento delle attività previste dalle metodologie precedentemente citate
prevede l'assunzione di ruoli specifici:

•	Facilitatore: è presente dal momento in cui il tester si accomoda fino ai saluti finali; ha il compito di introdurre e guidare il tester nelle attività di valutazione, di definire le regole da far rispettare durante lo svolgimento dei compiti; è inoltre disponibile per offrire chiarimenti su dubbi da parte del tester;

•	Osservatore: è presente durante l’intervista e non partecipa attivamente all’attività di valutazione, in quanto non interagisce con il partecipante; l'osservatore ha il compito di prendere nota dei comportamenti del tester durante l’uso del sito e degli effetti del suo modo di interagire con questo durante lo svolgimento dei compiti proposti;

Nello svolgimento delle attività di test, tutti membri del gruppo hanno svolto a rotazione sia il compito di facilitatore che di osservatore.

