= Relazione Test di Usabilità: Valutazione del sito web del comune di Taranto
Andrea Esposito <a.esposito39@studenti.uniba.it>; Alessandro Annese <a.annese23@studenti.uniba.it>; Davide De Salvo <d.desalvo@studenti.uniba.it>; Graziano Montanaro <g.montanaro16@studenti.uniba.it>; Regina Zaccaria <r.zaccaria14@studenti.uniba.it>
v1.0.0, 13 gennaio 2019: Completamento della stesura del documento
:toc: left
:doctype: book
:sectnums:
:partnums:
:sectnumsdepth: 5
:xrefstyle: short
:media: prepress
include::../locale/attributes.adoc[]
//:stem: latexmath

[colophon#colophon%nonfacing]
== {doctitle}

Copyright (C) {revdate} FSC. Tutti i diritti riservati. Versione {revnumber}.

Pubblicato autonomamente dal gruppo FSC ({authors}).

Concesso in licenza secondo i termini della Licenza Apache, versione 2.0 (la
"Licenza"); è proibito usare questo file se non in conformità alla Licenza. Una
copia della Licenza è disponibile all'indirizzo:

[.text-center]
http://www.apache.org/licenses/LICENSE-2.0

Se non richiesto dalla legislazione vigente o concordato per iscritto, il
software distribuito nei termini della Licenza è distribuito "`così com'è`",
__senza garanzie o condizioni di alcun tipo__, esplicite o implicite. Consultare
la Licenza per il testo specifico che regola le autorizzazioni e le limitazioni
previste dalla medesima.


[%hardbreaks]
*Autori:* {authors}
*Design copertina e interno:* {author}
*Referente del gruppo per il progetto:* {author}

include::content.adoc[]
